---

- name: install supervisor
  apt:
    update_cache: yes
    cache_valid_time: 600
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
    - supervisor

- name: enable/start supervisor
  service: >
    name=supervisor
    state=started
    enabled=yes
