---
- name: generate locale
  locale_gen: name={{ locale }} state=present

- name: set locale
  command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }} LANGUAGE={{ language }}

- name: set /etc/localtime
  copy: remote_src=True src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime

- name: set timezone (/etc/timezone)
  template: src=timezone dest=/etc/timezone
  notify: update tzdata
