---

- name: make sure service group exists
  group: >
    name="{{ service_group }}"
    state=present

- name: make sure service user exists
  user: >
    name={{ service_user }}
    password={{ service_user_password }}
    group={{ service_group }}
    shell=/bin/bash
