---
# setup nginx for gunicorn and static files

- name: remove nginx default site
  file: >
    path={{ nginx_config_path }}/sites-enabled/default
    state=absent
  notify:
   - restart nginx

- name: configure nginx django site
  template: >
    src="nginx.conf.j2"
    dest="{{ nginx_config_path }}/sites-available/{{ service_name }}.conf"
    owner={{ service_user }}
    group={{ service_group }}
    mode=0644
    backup=yes
  notify:
   - restart nginx

- name: enable nginx django/gunicorn site
  file: >
    src="{{ nginx_config_path }}/sites-available/{{ service_name }}.conf"
    dest="{{ nginx_config_path }}/sites-enabled/{{ service_name }}.conf"
    owner={{ service_user }}
    group={{ service_group }}
    state=link
  notify:
   - restart nginx

- name: disable apache
  service: name=apache2 state=stopped enabled=no
  when: install_apache|bool

- name: enable nginx
  service: name=nginx state=started enabled=yes
