---

- name: install postgis
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=600
  with_items:
    - postgresql-{{ postgres_version }}-postgis-2.4
    - postgresql-{{ postgres_version }}-postgis-scripts
