---

- name: install postgis
  apt:
    update_cache: yes
    cache_valid_time: 600
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
    - postgresql-{{ postgres_version }}-postgis-2.4
    - postgresql-{{ postgres_version }}-postgis-scripts
