---
# create database with user, run migrations and load sample data

- name: drop database
  become_user: "postgres"
  postgresql_db: >
    name={{ db_name }}
    state=absent
  tags:
    - drop_database
  when: not disabled_by_default

- name: create database
  become_user: "postgres"
  postgresql_db: >
    name={{ db_name }}
    template='template0'
    state=present
  when: use_postgresql|bool
  tags: create_database

- name: enable spatial extensions
  become_user: "postgres"
  postgresql_ext: name={{ item }} db={{ db_name }}
  with_items:
    - postgis
    #- postgis_topology
  when: use_postgresql and enable_postgis
  tags: create_database

- name: create database user
  become_user: "postgres"
  postgresql_user: >
    db={{ db_name }}
    name={{ db_user }}
    password={{ db_password }}
    priv=ALL
    role_attr_flags=INHERIT,CREATEDB,SUPERUSER
  when: use_postgresql|bool
  tags: create_database

- name: configure pgpass for {{ service_user }}
  become_user: "{{ service_user }}"
  lineinfile: >
    dest="~/.pgpass"
    line="localhost:*:{{ db_name }}:{{ db_user }}:{{ db_password }}"
    owner={{ service_user }}
    group={{ service_group }}
    mode=0600
    state=present
    create=yes
  when: use_postgresql|bool
  tags: create_database
