---

- name: install mscorefonts
  become_user: 'root'
  apt:
    update_cache: yes
    cache_valid_time: 600
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
    - ttf-mscorefonts-installer
  tags:
    - install_fonts

- name: install required tools
  become_user: 'root'
  apt:
    update_cache: yes
    cache_valid_time: 600
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
    - cabextract
  tags:
    - install_fonts

- name: create local fonts directory
  file: >
    path="{{ item }}"
    owner={{ service_user }}
    group={{ service_group }}
    mode=0755
    state=directory
  with_items:
    - "~{{ service_user }}/.fonts"
  tags:
    - install_fonts

- name: run vistafonts-installer
  become_user: "{{ service_user }}"
  script: vistafonts-installer.sh
  tags:
    - install_fonts
